# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- checkout: self
  fetchDepth: 0    
  # Step 1: Prepare the SonarCloud analysis environment
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloud1'
    organization: 'inversion-cycles'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: '2406f40a34c461b897d99ebc8b4e0d91855f4f3b'
    cliProjectName: 'FlipsoApp'
    cliSources: '.'
    extraProperties: |
      # Additional properties that will be passed to the scanner, 
      # Put one key=value per line, example:
      # sonar.exclusions=**/*.bin
      sonar.projectKey=manghos13_FlipsoApp
      sonar.projectName=FlipsoApp

- task: SonarCloudPublish@2
  inputs:
    pollingTimeoutSec: '300'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: SonarCloudAnalyze@2
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'   
- task: CopyFiles@2
  inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)'
      Contents: '**/target/*.war'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'
      publishLocation: 'Container'
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Free Trial(b51cce6b-b84f-4d51-8e70-291fd8cb28a0)'
    appType: 'webAppLinux'
    appName: 'my-web-app'
    package: '$(Build.ArtifactStagingDirectory)/**/*.war'
- task: Docker@2
  inputs:
    containerRegistry: 'mywebappcr1'
    repository: 'mywebapp'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
#- task: WhiteSource@21
 # inputs:
  #  cwd: '$(System.DefaultWorkingDirectory)'
   # projectName: 'FlipsoApp'
